In [109]:
from bs4 import BeautifulSoup
import requests
from urllib.parse import urljoin
import time
import pandas as pd

In [110]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

html = requests.get(url).content

df_list = pd.read_html(html)

df = df_list[0]

print(df)

df.to_csv('toronto_data.csv')

    Postal Code           Borough  \
0           M1A      Not assigned
1           M2A      Not assigned
2           M3A        North York
3           M4A        North York
4           M5A  Downtown Toronto
..          ...               ...
175         M5Z      Not assigned
176         M6Z      Not assigned
177         M7Z      Not assigned
178         M8Z         Etobicoke
179         M9Z      Not assigned

                                         Neighbourhood
0                                         Not assigned
1                                         Not assigned
2                                            Parkwoods
3                                     Victoria Village
4                            Regent Park, Harbourfront
..                                                 ...
175                                       Not assigned
176                                       Not assigned
177                                       Not assigned
178  Mimico NW, The Queensway West, South of Bloor,...
179                                       Not assigned

[180 rows x 3 columns]

In [111]:
df_toronto = pd.read_csv('toronto_data.csv')

In [112]:
df_toronto.head()

   Unnamed: 0 Postal Code           Borough              Neighbourhood
0           0         M1A      Not assigned               Not assigned
1           1         M2A      Not assigned               Not assigned
2           2         M3A        North York                  Parkwoods
3           3         M4A        North York           Victoria Village
4           4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [114]:
del df_toronto["Unnamed: 0"]
df_toronto.head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

DROP ROWS WITH BOROUGH NOT ASSIGNED

In [115]:
# Get indexes where Borough has value Not assigned
indexNames = df_toronto[df['Borough'] == 'Not assigned'].index
 
# Delete these row indexes from dataFrame
df_toronto.drop(indexNames , inplace=True)

In [116]:
df_toronto.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

SEARCH FOR ROWS WITH NEIGHBOURHOOD NOT ASSIGNED AND REPLACE WITH BOROUGH

In [117]:
# Replace Neighbourhood that has value Not assigned with Borough
df_toronto.Neighbourhood = df_toronto.Borough.where(df_toronto.Neighbourhood == 'Not assigned', df_toronto.Neighbourhood)

In [118]:
df_toronto.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [125]:
df_toronto.rename(columns={'Postal Code':'PostalCode'}, inplace=True)
df_toronto.head()

  PostalCode           Borough                                Neighbourhood
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [122]:
coordinates = pd.read_csv("https://cocl.us/Geospatial_data")
print(coordinates)

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [123]:
coordinates.rename(columns={'Postal Code':'PostalCode'}, inplace=True)
coordinates

    PostalCode   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
..         ...        ...        ...
98         M9N  43.706876 -79.518188
99         M9P  43.696319 -79.532242
100        M9R  43.688905 -79.554724
101        M9V  43.739416 -79.588437
102        M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [129]:
latitude_dict = dict(coordinates[['PostalCode', 'Latitude']].values)
df_toronto['Latitude'] = coordinates.PostalCode.map(latitude_dict)

longitude_dict = dict(coordinates[['PostalCode', 'Longitude']].values)
df_toronto['Longitude'] = coordinates.PostalCode.map(longitude_dict)

df_toronto

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
2,M3A,North York,Parkwoods,43.763573,-79.188711
3,M4A,North York,Victoria Village,43.770992,-79.216917
4,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.773136,-79.239476
5,M6A,North York,"Lawrence Manor, Lawrence Heights",43.744734,-79.239476
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.727929,-79.262029
...,...,...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",NaN,NaN
165,M4Y,Downtown Toronto,Church and Wellesley,NaN,NaN
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",NaN,NaN
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",NaN,NaN
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",NaN,NaN

In [130]:
df_toronto = df_toronto[df_toronto['Latitude'].notna()]
df_toronto

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
2,M3A,North York,Parkwoods,43.763573,-79.188711
3,M4A,North York,Victoria Village,43.770992,-79.216917
4,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.773136,-79.239476
5,M6A,North York,"Lawrence Manor, Lawrence Heights",43.744734,-79.239476
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.727929,-79.262029
...,...,...,...,...,...
95,M6N,York,"Runnymede, The Junction North",43.643515,-79.577201
98,M9N,York,Weston,43.706876,-79.518188
99,M1P,Scarborough,"Dorset Park, Wexford Heights, Scarborough Town...",43.696319,-79.532242
100,M2P,North York,York Mills West,43.688905,-79.554724
102,M4P,Central Toronto,Davisville North,43.706748,-79.594054

In [131]:
df_toronto = df_toronto.reset_index(drop=True)
df_toronto

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.763573,-79.188711
1,M4A,North York,Victoria Village,43.770992,-79.216917
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.773136,-79.239476
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.744734,-79.239476
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.727929,-79.262029
...,...,...,...,...,...
63,M6N,York,"Runnymede, The Junction North",43.643515,-79.577201
64,M9N,York,Weston,43.706876,-79.518188
65,M1P,Scarborough,"Dorset Park, Wexford Heights, Scarborough Town...",43.696319,-79.532242
66,M2P,North York,York Mills West,43.688905,-79.554724
67,M4P,Central Toronto,Davisville North,43.706748,-79.594054